channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.8
  - scikit-learn>=1.0.0  # Updated for Python 3.12 compatibility
  - pip
  - pip:
    - mlflow>=2.9.0  # Use recent MLflow version
    - cloudpickle>=2.0.0  # Updated version
name: mlflow-env
